# This file was generated by the `rspec --init` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# Require this file using `require "spec_helper"` to ensure that it is only
# loaded once.
#
# See http://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration

require 'active_record'

def relative_path(path)
  File.join File.dirname(__FILE__), path
end

config = YAML::load(IO.read(relative_path 'database.yml'))
ActiveRecord::Base.logger = Logger.new(relative_path "debug.log")
ActiveRecord::Base.establish_connection(config['rude_q_test'])

load(relative_path "schema.rb")
require 'models/rude_queue'
require 'models/something'

RSpec.configure do |config|
  config.treat_symbols_as_metadata_keys_with_true_values = true
  config.run_all_when_everything_filtered = true
  config.filter_run :focus

  # Run specs in random order to surface order dependencies. If you find an
  # order dependency and want to debug it, you can fix the order by providing
  # the seed, which is printed after each run.
  #     --seed 1234
  config.order = 'random'
end

